// <auto-generated />
using System;
using Learnaptic.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Learnaptic.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260627075057_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Learnaptic.Api.Models.Concept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudyGuideId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudyGuideId");

                    b.ToTable("Concepts");
                });

            modelBuilder.Entity("Learnaptic.Api.Models.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudyGuideId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudyGuideId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("Learnaptic.Api.Models.KeyPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConceptId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.ToTable("KeyPoints");
                });

            modelBuilder.Entity("Learnaptic.Api.Models.StudyGuide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("StudyGuides");
                });

            modelBuilder.Entity("Learnaptic.Api.Models.Concept", b =>
                {
                    b.HasOne("Learnaptic.Api.Models.StudyGuide", "StudyGuide")
                        .WithMany("Concepts")
                        .HasForeignKey("StudyGuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyGuide");
                });

            modelBuilder.Entity("Learnaptic.Api.Models.Flashcard", b =>
                {
                    b.HasOne("Learnaptic.Api.Models.StudyGuide", "StudyGuide")
                        .WithMany("Flashcards")
                        .HasForeignKey("StudyGuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyGuide");
                });

            modelBuilder.Entity("Learnaptic.Api.Models.KeyPoint", b =>
                {
                    b.HasOne("Learnaptic.Api.Models.Concept", "Concept")
                        .WithMany("KeyPoints")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");
                });

            modelBuilder.Entity("Learnaptic.Api.Models.Concept", b =>
                {
                    b.Navigation("KeyPoints");
                });

            modelBuilder.Entity("Learnaptic.Api.Models.StudyGuide", b =>
                {
                    b.Navigation("Concepts");

                    b.Navigation("Flashcards");
                });
#pragma warning restore 612, 618
        }
    }
}
