@Learnaptic.Api_HostAddress = http://localhost:5075
@notebookId = 1
@studySetId = 1
@conceptId = 1

###############################################
# STUDY GUIDES
###############################################

### Get all Study Guides
GET {{Learnaptic.Api_HostAddress}}/api/study-guides
Accept: application/json


### Get a specific Study Guide by ID
GET {{Learnaptic.Api_HostAddress}}/api/study-guides/{{notebookId}}
Accept: application/json


### Create a new Study Guide
POST {{Learnaptic.Api_HostAddress}}/api/notebooks
Content-Type: application/json
{
  "title": "Biology Exam Review",
  "subject": "Biology",
  "color": "teal",
}


### Update an existing Study Guide
PUT {{Learnaptic.Api_HostAddress}}/api/study-guides/{{notebookId}}
Content-Type: application/json
{
  "title": "Updated Biology Exam Review"
}


### Delete a Study Guide
DELETE {{Learnaptic.Api_HostAddress}}/api/study-guides/{{notebookId}}


###############################################
# CONCEPTS
###############################################


### Create a new Concept for a Study Guide
POST {{Learnaptic.Api_HostAddress}}/api/study-guides/{{notebookId}}/concepts
Content-Type: application/json
{
  "title": "Cell Division",
  "content": "The process by which a parent cell divides into two or more daughter cells."
}


### Update an existing Concept for a Study Guide
PUT {{Learnaptic.Api_HostAddress}}/api/study-guides/{{notebookId}}/concepts/{{conceptId}}
Content-Type: application/json
{
  "title": "Updated Cell Division",
  "content": "The process by which a parent cell divides into two or more daughter cells."
}


### Reorder concepts in Study Guide
PUT {{Learnaptic.Api_HostAddress}}/api/study-guides/{{notebookId}}/concepts/reorder
Content-Type: application/json
[4,6,7,3]

###############################################
# STUDY SETS
###############################################

### Get all Study Sets
GET {{Learnaptic.Api_HostAddress}}/api/study-sets
Accept: application/json


### Get a specific Study Set by ID
GET {{Learnaptic.Api_HostAddress}}/api/study-sets/{{studySetId}}
Accept: application/json


### Create a new Study Set
POST {{Learnaptic.Api_HostAddress}}/api/study-sets
Content-Type: application/json

{
  "title": "Biology Study Set",
  "notebookIds": [],
  "flashcards": [
    {
      "question": "What is mitosis?",
      "answer": "The process in which a cell divides to produce two genetically identical daughter cells."
    },
    {
      "question": "What is photosynthesis?",
      "answer": "The process plants use to convert light energy into chemical energy."
    },
    {
      "question": "What is DNA?",
      "answer": "A molecule that carries genetic information."
    }
  ]
}


### Update an existing Study Set
PUT {{Learnaptic.Api_HostAddress}}/api/study-sets/{{studySetId}}
Content-Type: application/json

{
  "title": "Updated Biology Study Set",
  "notebookIds": [],
  "flashcards": [
    {
      "id": 2,
      "question": "What is photosynthesis?",
      "answer": "The process plants use to convert light energy into chemical energy."
    },
    {
      "id": 1,
      "question": "What is mitosis?",
      "answer": "Mitosis is the process in which a cell divides to produce two genetically identical daughter cells."
    },
    {
      "question": "What is RNA?",
      "answer": "A molecule that plays a role in coding, decoding, regulation, and expression of genes."
    }
  ]
}


### Delete a Study Set
DELETE {{Learnaptic.Api_HostAddress}}/api/study-sets/{{studySetId}}


###############################################
# AUTH
###############################################


### Register a new user
POST {{Learnaptic.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "userName": "StudyWizard2",
  "email": "studywizard2@example.com",
  "password": "ExamplePassword123!"
}

### Login an existing user
POST {{Learnaptic.Api_HostAddress}}/api/auth/login
Content-Type: application/json
{
  "email": "studywizard@example.com",
  "password": "ExamplePassword123!"
}

### Authorize a user with a token
GET {{Learnaptic.Api_HostAddress}}/api/auth/me

### Logout a user
POST {{Learnaptic.Api_HostAddress}}/api/auth/logout